version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: zero
      POSTGRES_PASSWORD: root
      POSTGRES_DB: zero
    ports:
      - "5432:5432"


volumes:
  postgres_data: